services:
  wordpress:
    image: wordpress
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: #RDS endpoint
      WORDPRESS_DB_USER: #master username
      WORDPRESS_DB_PASSWORD: #master password
      WORDPRESS_DB_NAME: #initial database name